services:

  db:
    image: postgres:12
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: northwind_user
      POSTGRES_PASSWORD: thewindisblowing
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./db-init/northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
      - ./db-init/airflow.sql:/docker-entrypoint-initdb.d/airflow.sql
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow_user", "-d", "airflow_db"]
      interval: 10s
      timeout: 5s
      retries: 5

# pgadmin if need to connect to db
#  pgadmin:
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#    ports:
#    - 80:80


  meltano:
    container_name: meltano-container
    # image: meltano-image
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
    volumes:
      - ./output:/project/my-project/output
      - ./data:/project/my-project/data
      - ./tmpdata:/project/my-project/tmpdata
    restart: on-failure
